default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: jackson-db.cnogmeg6ga0c.us-east-1.rds.amazonaws.com
      user: postgres
      password: hyjvaf-Mojgyg-turxe0
      port: 5432
      dbname: GOLD
      schema: PLATFORM
      threads: 1
